name: Deploy Weather Folder

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Pages artifact (weather folder)
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./weather
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
